- name: Copy redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis
  ansible.builtin.yum:
    name: redis-6.2.11
    state: installed

- name: Replace IP address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
   - /etc/redis/conf
   - /etc/redis/redis.conf

- name: Restart service
  ansible.builtin.service:
    name: redis
    state: restarted